### ISSUE TITLE
Interactive demo won't work

### ISSUE THREAD

**Issue by curlup** [Networks-Learning/RedQueen-website#1]
I think the problem might be somewhere here

![image](https://cloud.githubusercontent.com/assets/338607/23060113/6618ba36-f50d-11e6-8613-b0b29a9fcfab.png)

Google Chrome Version 50.0.2661.86 (64-bit)

**Comment by musically-ut** [comment]
Thanks for the report!

Could you also please tell me which version of Chrome are you using?

I've replaced `Object.values` with a hand-rolled out version which ought to fix the problem. Kindly close the issue if that resolves the problem.

**Comment by curlup** [comment]
works now
